require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.plugconfig"
require "user.compare"
require "user.lsp"
require "user.telescope"
require "user.treesitter"
require "user.lualine"
require "user.autopairs"
require "user.bufferline"
require "user.toggleterm"
-- require "user.tree"
-- require "user.diffview"
